[kmooc_ing]
title = "K-MOOC ─ 진행중"
url = "http://www.kmooc.kr/courses?range=i"
entrySelector = "li.courses-listing-item"
titleSelector = "span.course-title.kr01-Msilder-title"
linkSelector = "article.course.ing a"
contentSelector = "div.course-date.kr01_moviesubtit"
imageSelector = "div.cover-image img"
waitUntil = "networkidle"

[kmooc_soon]
title = "K-MOOC ─ 개강예정"
url = "http://www.kmooc.kr/courses?range=t"
entrySelector = "li.courses-listing-item"
titleSelector = "span.course-title.kr01-Msilder-title"
linkSelector = "article.course.ing a"
contentSelector = "div.course-date.kr01_moviesubtit"
imageSelector = "div.cover-image img"
waitUntil = "networkidle"